#!/bin/bash -eu

SCRIPT=`readlink -f $0`; SCRIPTPATH=`dirname "$SCRIPT"`; cd "$SCRIPTPATH";
if [ "$0" != "./build-package" ]; then
  echo "Must be run from containing directory NOT $0";
  exit 1;
fi
echo "BUILDING..."
sudo chown -R root:root debian/etc;
sudo chown -R www-data:www-data debian/var/www/*;
sudo dpkg-deb --build debian;
echo "renaming 'debian.deb' to 'apache2-webshop-conf-0.1_all.deb'";
mv debian.deb apache2-webshop-conf-0.1_all.deb;
sudo chmod 775 apache2-webshop-conf-0.1_all.deb;
sudo chown ${USER}:${USER} apache2-webshop-conf-0.1_all.deb
sudo chown -R ${USER}:${USER} debian;
echo "BUILD SUCCESFULLY COMPLETED!";
