#!/bin/bash

. /usr/share/debconf/confmodule
db_version 2.0
db_capb backup

db_input high apache2-web-conf/remote_ips || true
db_title "List of remote IP addresses that requier 'dev.' access:"
db_go || true
