#!/bin/bash

if [ -d /etc/apache2/ ]; then
  service apache2 reload;
fi

if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
    # Source debconf library.
    . /usr/share/debconf/confmodule
    db_purge
fi

exit 0;
