#!/bin/bash

. /usr/share/debconf/confmodule
db_get apache2-web-conf/remote_ips
REMOTE_IPS="$RET";

echo "UPDATING /etc/apache2/sites-available/default";
if [ -f /etc/apache2/sites-available/000-default.conf ]; then
  sudo mv /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available_000-default.conf.dpkg-old;
fi
sudo cp /tmp/apache2-webshop-conf/etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/000-default.conf

echo "CONFIGURING APACHE2 ENVVARS";
if [ -f /etc/apache2/envvars ]; then
  sudo cp /etc/apache2/envvars /etc/apache2/envvars.dpkg-old;
fi
sudo echo "export HOSTNAME=\"${HOSTNAME}\"" >> /etc/apache2/envvars;

echo "CONFIGURING symlink for ChromePhp";
sudo ln -s /usr/share/php/ChromePhp.php /usr/share/php/ChromePhp.class.php;

echo "ADDING APACHE MODULES";
sudo a2enmod vhost_alias rewrite headers deflate setenvif filter expires include ssl;

echo "SETTING 'ServerTokens' to 'Prod' IN '/etc/apache2/conf-available/security'";
sudo mv /etc/apache2/conf-available/security.conf /etc/apache2/conf-available_security.conf.dpkg-old;
sudo awk '{sub("^ServerTokens [A-Z|a-z]+", "ServerTokens Prod");print}' /etc/apache2/conf-available_security.conf.dpkg-old > /etc/apache2/conf-available/security.conf;

echo "SETTING 'expose_php = Off' AND 'date.timezone = Europe/London' IN '/etc/php/*/apache2/php.ini'";
for f in /etc/php/*/apache2/php.ini; do
  sudo mv "$f" "${f%}.dpkg-old"
  sudo awk '{sub("^expose_php = O(n|ff)", "expose_php = Off");sub("^(;)date.timezone =*", "date.timezone = Europe/London");print}' /etc/php/${f%}/apache2/php.ini.dpkg-old > /etc/php/${f%}/apache2/php.ini;
done

echo "SETTING 'date.timezone = Europe/London' IN '/etc/php/*/cli/php.ini'";
for f in /etc/php/*/cli/php.ini; do
  sudo mv "$f" "${f%}.dpkg-old"
  sudo awk '{sub("^(;)date.timezone =*", "date.timezone = Europe/London");print}' /etc/php/${f%}/cli/php.ini.dpkg-old > /etc/php/${f%}/cli/php.ini;
done

echo 'CONFIGURING access for the following IP addresses:';
for IP in ${REMOTE_IPS}; do
  echo " $IP";
  sed -e "s/# Allowed remote access IP addresses/# Allowed remote access IP addresses\n  Require ip $IP/g" /etc/apache2/conf-available/webshop.local.conf > /etc/apache2/conf-available/webshop.local.conf.tmp && mv /etc/apache2/conf-available/webshop.local.conf.tmp /etc/apache2/conf-available/webshop.local.conf
done;

echo "ADDING SERVER SSL CERTIFICATE" 
sudo ufw allow 'Apache Full';
sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/apache-selfsigned.key -out /etc/ssl/certs/apache-selfsigned.crt;
#sudo certbot --apache

sudo a2enconf webshop.local;

echo "RESTARTING MODIFIED SERVICES";
sudo service apache2 reload;
exit 0;
